stages:
  - build

variables:
  CONTAINER_IMAGE: ergw/vpp
  CI_REGISTRY: index.docker.io  # container registry URL
  CI_REGISTRY_IMAGE: https://index.docker.io/v1/


# build container image
.build:
  stage: build
  #tags:
  #  - docker
  image: docker:git
  services:
  - docker:dind
  script:
    - export CI_COMMIT_DESCRIBE=$(git describe --always --tags --dirty --first-parent)
    - export CONTAINER_VARIANT=${CI_BUILD_NAME##*:}
    - export CONTAINER_BASE_NAME=${CONTAINER_IMAGE}:${CI_COMMIT_REF_SLUG}
    - export CONTAINER_COMMIT_SHA=${CONTAINER_BASE_NAME}_${CI_COMMIT_SHA}_${CONTAINER_VARIANT}
    - export CONTAINER_GIT_DESCRIBE=${CONTAINER_BASE_NAME}_${CI_COMMIT_DESCRIBE}_${CONTAINER_VARIANT}
    - export DOCKER_HOST="tcp://localhost:2375"
    - echo "Docker HUB login..."
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - echo "Building the image from $DOCKER_FILE ..."
    - >
      DOCKER_BUILDKIT=1 docker build
      --target=build-stage
      -t  artifacts:${CI_COMMIT_SHA}_${CONTAINER_VARIANT}
      -f ${DOCKER_FILE} .
    - >
      DOCKER_BUILDKIT=1 docker build
      --progress=plain
      -t ${CONTAINER_COMMIT_SHA}
      -t ${CONTAINER_GIT_DESCRIBE}
      -f ${DOCKER_FILE} .
    - docker push ${CONTAINER_COMMIT_SHA}
    - docker push ${CONTAINER_GIT_DESCRIBE}
    - echo "Extracting *.deb files from the image ..."
    - mkdir debs
    - >
      DOCKER_BUILDKIT=1 docker run
      --rm artifacts:${CI_COMMIT_SHA}_${CONTAINER_VARIANT} | tar -C "debs" -xf -
  artifacts:
    when: always
    untracked: true
    paths:
      - debs

# build container image
build:release:
  extends: .build
  variables:
    DOCKER_FILE: extras/docker/Dockerfile

build:debug:
  extends: .build
  variables:
    DOCKER_FILE: extras/docker/Dockerfile.devel
